# Week 10 Challenge : 

### Q1.Create two numpy arrays. The first array, called arr1 should be of one dimension and consist of six elements of float type. The second array, called arr2 should be of two dimensions and each sub-array should consist of 5 elements of string type. Display these two numpy arrays.

In [69]:
import numpy as np
arr1 = np.arange(6, dtype= float)
print('one dimensional array : ', arr1)

arr2 = np.array([['rahul','ganesh','ramesh','mehul','harry','hitesh'],
                 ['hemant','harry','joy','karan','lokesh','kurama'] ], dtype = str)
print('Two dimensional array : ', arr2)

one dimensional array :  [0. 1. 2. 3. 4. 5.]
Two dimensional array :  [['rahul' 'ganesh' 'ramesh' 'mehul' 'harry' 'hitesh']
 ['hemant' 'harry' 'joy' 'karan' 'lokesh' 'kurama']]


# --------------------------------------------------------------------------------------------------------------

### Q2. For the arrays arr1 and arr2 created in Q.No.1, display the following properties: data type and dimensions. Reshape arr1 into a two dimensional array of 2 rows and three columns, and display the reshaped array. Similarly, reshape arr2 into a single dimensional array and display the reshaped array.

In [26]:
print('Data type of arr1 : ', arr1.dtype)
print('Data type of arr2 : ', arr2.dtype)
print('Dimensions of arr1 : ',arr1.shape)
print('Dimensions of arr2 : ',arr2.shape)

print('-'*120)
# 1-D array into 2-D array 
a1 = arr1.reshape(2,3)
print('Reshaped array arr1  : ',a1)
print('Dimension of reshaped array arr1 : ', a1.shape)
print('-'*120)

# 2- D Array into 1- D Array 
a2 = arr2.reshape(12,)
print('Reshaped array arr2 : ',a2)
print('Dimension of reshaped array arr2 : ', a2.shape)

Data type of arr1 :  float64
Data type of arr2 :  <U6
Dimensions of arr1 :  (6,)
Dimensions of arr2 :  (2, 6)
------------------------------------------------------------------------------------------------------------------------
Reshaped array arr1  :  [[0. 1. 2.]
 [3. 4. 5.]]
Dimension of reshaped array arr1 :  (2, 3)
------------------------------------------------------------------------------------------------------------------------
Reshaped array arr2 :  ['rahul' 'ganesh' 'ramesh' 'mehul' 'harry' 'hitesh' 'hemant' 'harry' 'joy'
 'karan' 'lokesh' 'kurama']
Dimension of reshaped array arr2 :  (12,)


# --------------------------------------------------------------------------------------------------------------

### Q3.Create a two dimensional array called arr3, of 3 rows and 4 columns which is initialized to zeroes. Create another single dimensional array called arr4, with 6 elements and which is initialized to ones. The type of arr4 is int

In [68]:
# creating an array with zeros .
arr3 = np.zeros((3,4))
print( arr3)
print('-'*120)

# creating an array with ones 
arr4 = np.ones((6,) , dtype = int)
print(arr4)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
------------------------------------------------------------------------------------------------------------------------
[1 1 1 1 1 1]


# ---------------------------------------------------------------------------------------------------------------

### Q4. Create a list called list1 with the elements 10,20,30,40,50. Now, create a numpy array called arr5 from list1, using the method asarray. The data type of arr5 is float. Similarly, create another array called arr6, from list1, using the method fromiter, whose data type is int. Display arr5 and arr6.

In [32]:
# creating an array from list 

list1 = [10,20,30,40,50]

arr5 = np.asarray(list1 , dtype = float )
print(arr5)
print('-'*120)

arr6 = np.asarray(list1 , dtype = int)
print(arr6)


[10. 20. 30. 40. 50.]
------------------------------------------------------------------------------------------------------------------------
[10 20 30 40 50]


# ------------------------------------------------------------------------------------------------------------

### Q5. Create a numpy array called arr7 using the method arange. The starting value of this array is 12 and ending value is 99, with a step size of 3. Use the linspace method to create another array called arr8, where the starting value is 12 and ending value is 99 and which contains 50 evenly spaced elements.

In [36]:
# creating array using arange 

arr7 = np.arange(12,100,3)
print(arr7)
print('-'*120)

# creating an array using linspace 
arr8 = np.linspace(12,99,50)
print(arr8)

[12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81
 84 87 90 93 96 99]
------------------------------------------------------------------------------------------------------------------------
[12.         13.7755102  15.55102041 17.32653061 19.10204082 20.87755102
 22.65306122 24.42857143 26.20408163 27.97959184 29.75510204 31.53061224
 33.30612245 35.08163265 36.85714286 38.63265306 40.40816327 42.18367347
 43.95918367 45.73469388 47.51020408 49.28571429 51.06122449 52.83673469
 54.6122449  56.3877551  58.16326531 59.93877551 61.71428571 63.48979592
 65.26530612 67.04081633 68.81632653 70.59183673 72.36734694 74.14285714
 75.91836735 77.69387755 79.46938776 81.24489796 83.02040816 84.79591837
 86.57142857 88.34693878 90.12244898 91.89795918 93.67346939 95.44897959
 97.2244898  99.        ]


# --------------------------------------------------------------------------------------------------------------

### Q6.In the array arr2 defined in Q.No. 1, what is the output of the following statements: print(arr2), print(arr2[0:1]), print(arr2[1][3]), print (arr2[1])

In [37]:
print('output of arr2 :' ,arr2)
print('output of arr2[0:1] : ',arr2[0:1])
print('ouput of arr2[1][3] : ', arr2[1][3])
print('Output of arr2[1] : ', arr2[1])

output of arr2 : [['rahul' 'ganesh' 'ramesh' 'mehul' 'harry' 'hitesh']
 ['hemant' 'harry' 'joy' 'karan' 'lokesh' 'kurama']]
output of arr2[0:1] :  [['rahul' 'ganesh' 'ramesh' 'mehul' 'harry' 'hitesh']]
ouput of arr2[1][3] :  karan
Output of arr2[1] :  ['hemant' 'harry' 'joy' 'karan' 'lokesh' 'kurama']


# --------------------------------------------------------------------------------------------------------------

### Q7.Create a two dimensional array called arr9 with the following elements: [101, 322, 768], [233, 124, 390], [534, 122, 216]. From arr9, create an array called arr10 which contains the elements 101, 322, 390, 122 using advanced integer indexing. Create another array called arr11 which contains elements of first and second rows, and second and third columns using slicing operations.

In [48]:
# Advanced integer indexing 

arr9 = np.array([[101, 322, 768], [233, 124, 390],[534,122,216]])
print('The array is : ')
print(arr9)
arr10 = arr9[[0,0,1,2],[0,1,2,1]]
print('Array arr10 : ',arr10)
print('-'*120)
print('The array is :')
arr11 = arr9[0:2,[1,2]]
print(arr11)

The array is : 
[[101 322 768]
 [233 124 390]
 [534 122 216]]
Array arr10 :  [101 322 390 122]
------------------------------------------------------------------------------------------------------------------------
The array is :
[[322 768]
 [124 390]]


# -------------------------------------------------------------------------------------------------------------

### Q8.From array arr9 created in Q.No. 7, find all elements greater than 200 using boolean indexing, find all non-NaN elements, and find all non-float elements. Find the result of adding arrays arr9 and another array of 3 elements, using the concept of broadcasting.

In [66]:
# Elements greater than 200 in arr9 : 
print('The elements greater than 200  in arr9 are :',arr9[arr9 > 200])
print('-' * 120)
print('Non NaN elements are : ', arr9[~np.isnan(arr9)])
print('All numbers in arr9 are non-float numbers')
print('-'*120)
array1 = np.arange(3)

print('Result of adding arr9 and array1 : ') 
print(arr9 + array1)

The elements greater than 200  in arr9 are : [322 768 233 390 534 216]
------------------------------------------------------------------------------------------------------------------------
Non NaN elements are :  [101 322 768 233 124 390 534 122 216]
All numbers in arr9 are non-float numbers
------------------------------------------------------------------------------------------------------------------------
Result of adding arr9 and array1 : 
[[101 323 770]
 [233 125 392]
 [534 123 218]]


# -------------------------------------------------------------------------------------------------------------

### Q9.For the array arr9, find its transpose. Find the result of joining the arrays arr1 and arr4 along axis 0.

In [73]:
# Transpose of arr9 
print('Transpose of arr9 is : ')
print(arr9.T)
print('-' *120)
print('Results of joining arr1 and arr4 is : ')
print(np.concatenate((arr1,arr4), axis = 0))

Transpose of arr9 is : 
[[101 233 534]
 [322 124 122]
 [768 390 216]]
------------------------------------------------------------------------------------------------------------------------
Results of joining arr1 and arr4 is : 
[0. 1. 2. 3. 4. 5. 1. 1. 1. 1. 1. 1.]


# --------------------------------------------------------------------------------------------------------------

### Q10. Using any two 2-dimensional arrays, demonstrate the working of the methods, hstack, vstack, hsplit and vsplit.

In [83]:
# creating a two dimensional array 

myarray = np.array([[1,2,3,4,5,6,7,8],[4,5,6,1,2,3,7,8],[4,5,6,1,2,3,7,8],[4,5,6,1,2,3,9,2]])
print(myarray)
print('-'*120)

# hstack 
myarray_h_stack = np.hstack((myarray,myarray))
print('Result of hstack array is : ')
print(myarray_h_stack)
print('-'*120)

# vstack 
myarray_v_stack = np.vstack((myarray,myarray))
print('Result of vstack array is : ')
print(myarray_v_stack)
print('-' * 120)

# hsplit 
myarray_h_split = np.hsplit(myarray,4)
print('Result of hsplit array is : ')
print(myarray_h_split)
print('-'*120)

# vsplit 
myarray_v_split = np.vsplit(myarray,4)
print('Result of vsplit array is : ')
print(myarray_v_split)



[[1 2 3 4 5 6 7 8]
 [4 5 6 1 2 3 7 8]
 [4 5 6 1 2 3 7 8]
 [4 5 6 1 2 3 9 2]]
------------------------------------------------------------------------------------------------------------------------
Result of hstack array is : 
[[1 2 3 4 5 6 7 8 1 2 3 4 5 6 7 8]
 [4 5 6 1 2 3 7 8 4 5 6 1 2 3 7 8]
 [4 5 6 1 2 3 7 8 4 5 6 1 2 3 7 8]
 [4 5 6 1 2 3 9 2 4 5 6 1 2 3 9 2]]
------------------------------------------------------------------------------------------------------------------------
Result of vstack array is : 
[[1 2 3 4 5 6 7 8]
 [4 5 6 1 2 3 7 8]
 [4 5 6 1 2 3 7 8]
 [4 5 6 1 2 3 9 2]
 [1 2 3 4 5 6 7 8]
 [4 5 6 1 2 3 7 8]
 [4 5 6 1 2 3 7 8]
 [4 5 6 1 2 3 9 2]]
------------------------------------------------------------------------------------------------------------------------
Result of hsplit array is : 
[array([[1, 2],
       [4, 5],
       [4, 5],
       [4, 5]]), array([[3, 4],
       [6, 1],
       [6, 1],
       [6, 1]]), array([[5, 6],
       [2, 3],
       [2, 3],
       [2